### ISSUE TITLE
Variables not being populated on Mac

### ISSUE THREAD

**Issue by joeyfeldberg** [okeuday/GEPD#5]
These variables are not populated on Mac
Erlang installed with brew
```
ERLANG_EI_PATH
ERLANG_ERTS_PATH
ERLANG_EI_INCLUDE_PATH
ERLANG_EI_LIBRARY_PATH
ERLANG_ERTS_INCLUDE_PATH
ERLANG_ERTS_LIBRARY_PATH
```

**Comment by okeuday** [comment]
That looks like a problem using the cmake build and I haven't been using the cmake build.  If you wanted to fix it and document how to use it in the README, pull requests are welcome!
